//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(item))]
    
    public partial class category
    {
        public category()
        {
            this.items = new HashSet<item>();
        }
    
    	[DataMember]
        public int categoryId { get; set; }
    	[DataMember]
        public string categoryName { get; set; }
    
    	[DataMember]
        public virtual ICollection<item> items { get; set; }
    }
}
