//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(department))]
    
    public partial class collectionPoint
    {
        public collectionPoint()
        {
            this.departments = new HashSet<department>();
        }
    
    	[DataMember]
        public string collectionPointId { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> time { get; set; }
    	[DataMember]
        public string address { get; set; }
    
    	[DataMember]
        public virtual ICollection<department> departments { get; set; }
    }
}
