//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(collectionPoint))]
    [KnownType(typeof(disbursement))]
    [KnownType(typeof(requisition))]
    [KnownType(typeof(user))]
    
    public partial class department
    {
        public department()
        {
            this.disbursements = new HashSet<disbursement>();
            this.requisitions = new HashSet<requisition>();
            this.users = new HashSet<user>();
        }
    
    	[DataMember]
        public string departmentId { get; set; }
    	[DataMember]
        public string deptName { get; set; }
    	[DataMember]
        public string contacName { get; set; }
    	[DataMember]
        public string phoneNo { get; set; }
    	[DataMember]
        public string faxNo { get; set; }
    	[DataMember]
        public string collectionPointId { get; set; }
    
    	[DataMember]
        public virtual collectionPoint collectionPoint { get; set; }
    	[DataMember]
        public virtual ICollection<disbursement> disbursements { get; set; }
    	[DataMember]
        public virtual ICollection<requisition> requisitions { get; set; }
    	[DataMember]
        public virtual ICollection<user> users { get; set; }
    }
}
