//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(disbursement))]
    [KnownType(typeof(item))]
    
    public partial class disbursement_item
    {
    	[DataMember]
        public int disburse_itemId { get; set; }
    	[DataMember]
        public int disbursementId { get; set; }
    	[DataMember]
        public int itemId { get; set; }
    	[DataMember]
        public int collectQty { get; set; }
    
    	[DataMember]
        public virtual disbursement disbursement { get; set; }
    	[DataMember]
        public virtual item item { get; set; }
    }
}
