//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(discrepancy))]
    [KnownType(typeof(item))]
    
    public partial class discrepancy_item
    {
    	[DataMember]
        public int discrepancy_item1 { get; set; }
    	[DataMember]
        public int discrepancyId { get; set; }
    	[DataMember]
        public int itemId { get; set; }
    	[DataMember]
        public int reportQty { get; set; }
    	[DataMember]
        public string type { get; set; }
    
    	[DataMember]
        public virtual discrepancy discrepancy { get; set; }
    	[DataMember]
        public virtual item item { get; set; }
    }
}
