//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(discrepancy_item))]
    [KnownType(typeof(user))]
    
    public partial class discrepancy
    {
        public discrepancy()
        {
            this.discrepancy_item = new HashSet<discrepancy_item>();
        }
    
    	[DataMember]
        public int discrepancyId { get; set; }
    	[DataMember]
        public System.DateTime reportDate { get; set; }
    	[DataMember]
        public string Remark { get; set; }
    	[DataMember]
        public string userId { get; set; }
    	[DataMember]
        public int totalPrice { get; set; }
    	[DataMember]
        public string status { get; set; }
    
    	[DataMember]
        public virtual ICollection<discrepancy_item> discrepancy_item { get; set; }
    	[DataMember]
        public virtual user user { get; set; }
    }
}
