//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(category))]
    [KnownType(typeof(disbursement_item))]
    [KnownType(typeof(discrepancy_item))]
    [KnownType(typeof(item_supplier))]
    [KnownType(typeof(purchase_item))]
    [KnownType(typeof(requsiiton_item))]
    
    public partial class item
    {
        public item()
        {
            this.disbursement_item = new HashSet<disbursement_item>();
            this.discrepancy_item = new HashSet<discrepancy_item>();
            this.item_supplier = new HashSet<item_supplier>();
            this.purchase_item = new HashSet<purchase_item>();
            this.requsiiton_item = new HashSet<requsiiton_item>();
        }
    
    	[DataMember]
        public int itemId { get; set; }
    	[DataMember]
        public string unit { get; set; }
    	[DataMember]
        public int categoryId { get; set; }
    	[DataMember]
        public string description { get; set; }
    	[DataMember]
        public int reorderlevel { get; set; }
    	[DataMember]
        public int reorderQty { get; set; }
    	[DataMember]
        public int balance { get; set; }
    	[DataMember]
        public string binNumber { get; set; }
    	[DataMember]
        public string photourl { get; set; }
    
    	[DataMember]
        public virtual category category { get; set; }
    	[DataMember]
        public virtual ICollection<disbursement_item> disbursement_item { get; set; }
    	[DataMember]
        public virtual ICollection<discrepancy_item> discrepancy_item { get; set; }
    	[DataMember]
        public virtual ICollection<item_supplier> item_supplier { get; set; }
    	[DataMember]
        public virtual ICollection<purchase_item> purchase_item { get; set; }
    	[DataMember]
        public virtual ICollection<requsiiton_item> requsiiton_item { get; set; }
    }
}
