//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(item))]
    [KnownType(typeof(supplier))]
    
    public partial class item_supplier
    {
    	[DataMember]
        public int item_supplierId { get; set; }
    	[DataMember]
        public Nullable<int> itemId { get; set; }
    	[DataMember]
        public Nullable<int> supplierId { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> tenderYear { get; set; }
    	[DataMember]
        public Nullable<int> priority { get; set; }
    	[DataMember]
        public Nullable<int> price { get; set; }
    
    	[DataMember]
        public virtual item item { get; set; }
    	[DataMember]
        public virtual supplier supplier { get; set; }
    }
}
