//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    
    public partial class LogicUnivSystemEntities : DbContext
    {
    	public LogicUnivSystemEntities()
            : this(false) { }
    
        public LogicUnivSystemEntities(bool proxyCreationEnabled)
            : base("name=LogicUnivSystemEntities")
        {
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }
    	
        public LogicUnivSystemEntities(string connectionString)
          : this(connectionString, false) { }
    	  
        public LogicUnivSystemEntities(string connectionString, bool proxyCreationEnabled)
            : base(connectionString)
        {
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }	
    	
        public ObjectContext ObjectContext
        {
          get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<collectionPoint> collectionPoints { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<disbursement> disbursements { get; set; }
        public virtual DbSet<disbursement_item> disbursement_item { get; set; }
        public virtual DbSet<discrepancy> discrepancies { get; set; }
        public virtual DbSet<discrepancy_item> discrepancy_item { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<item_supplier> item_supplier { get; set; }
        public virtual DbSet<purchase> purchases { get; set; }
        public virtual DbSet<purchase_item> purchase_item { get; set; }
        public virtual DbSet<requisition> requisitions { get; set; }
        public virtual DbSet<requsiiton_item> requsiiton_item { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
