//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(purchase_item))]
    [KnownType(typeof(supplier))]
    [KnownType(typeof(user))]
    
    public partial class purchase
    {
        public purchase()
        {
            this.purchase_item = new HashSet<purchase_item>();
        }
    
    	[DataMember]
        public int purchaserId { get; set; }
    	[DataMember]
        public int supplierId { get; set; }
    	[DataMember]
        public System.DateTime purchaseDate { get; set; }
    	[DataMember]
        public string userId { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> expectedDeliveryDate { get; set; }
    	[DataMember]
        public string status { get; set; }
    
    	[DataMember]
        public virtual ICollection<purchase_item> purchase_item { get; set; }
    	[DataMember]
        public virtual supplier supplier { get; set; }
    	[DataMember]
        public virtual user user { get; set; }
    }
}
