//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(item))]
    [KnownType(typeof(purchase))]
    
    public partial class purchase_item
    {
    	[DataMember]
        public int reorder_orderId { get; set; }
    	[DataMember]
        public int purchaseId { get; set; }
    	[DataMember]
        public int itemId { get; set; }
    	[DataMember]
        public int requestQty { get; set; }
    
    	[DataMember]
        public virtual item item { get; set; }
    	[DataMember]
        public virtual purchase purchase { get; set; }
    }
}
