//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(department))]
    [KnownType(typeof(user))]
    [KnownType(typeof(requsiiton_item))]
    
    public partial class requisition
    {
        public requisition()
        {
            this.requsiiton_item = new HashSet<requsiiton_item>();
        }
    
    	[DataMember]
        public int requisitionId { get; set; }
    	[DataMember]
        public string departmentId { get; set; }
    	[DataMember]
        public System.DateTime requestDate { get; set; }
    	[DataMember]
        public string status { get; set; }
    	[DataMember]
        public string userId { get; set; }
    	[DataMember]
        public string rejectReason { get; set; }
    
    	[DataMember]
        public virtual department department { get; set; }
    	[DataMember]
        public virtual user user { get; set; }
    	[DataMember]
        public virtual ICollection<requsiiton_item> requsiiton_item { get; set; }
    }
}
