//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(item_supplier))]
    [KnownType(typeof(purchase))]
    
    public partial class supplier
    {
        public supplier()
        {
            this.item_supplier = new HashSet<item_supplier>();
            this.purchases = new HashSet<purchase>();
        }
    
    	[DataMember]
        public int supplierId { get; set; }
    	[DataMember]
        public string compName { get; set; }
    	[DataMember]
        public string contactName { get; set; }
    	[DataMember]
        public string phoneNo { get; set; }
    	[DataMember]
        public string faxNo { get; set; }
    	[DataMember]
        public string address { get; set; }
    	[DataMember]
        public string GST_RegistrationNo { get; set; }
    
    	[DataMember]
        public virtual ICollection<item_supplier> item_supplier { get; set; }
    	[DataMember]
        public virtual ICollection<purchase> purchases { get; set; }
    }
}
