//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryBL
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(department))]
    [KnownType(typeof(discrepancy))]
    [KnownType(typeof(purchase))]
    [KnownType(typeof(requisition))]
    [KnownType(typeof(role))]
    
    public partial class user
    {
        public user()
        {
            this.discrepancies = new HashSet<discrepancy>();
            this.purchases = new HashSet<purchase>();
            this.requisitions = new HashSet<requisition>();
        }
    
    	[DataMember]
        public string userId { get; set; }
    	[DataMember]
        public string name { get; set; }
    	[DataMember]
        public string password { get; set; }
    	[DataMember]
        public string email { get; set; }
    	[DataMember]
        public string phoneNo { get; set; }
    	[DataMember]
        public string address { get; set; }
    	[DataMember]
        public int roleId { get; set; }
    	[DataMember]
        public string departmentId { get; set; }
    
    	[DataMember]
        public virtual department department { get; set; }
    	[DataMember]
        public virtual ICollection<discrepancy> discrepancies { get; set; }
    	[DataMember]
        public virtual ICollection<purchase> purchases { get; set; }
    	[DataMember]
        public virtual ICollection<requisition> requisitions { get; set; }
    	[DataMember]
        public virtual role role { get; set; }
    }
}
